package shifter

//constants used
const (
	NullTag            = "null"
	PrimaryKeyTag      = "primary key"
	NotNullTag         = "not null"
	ReferencesTag      = "references"
	NoActionTag        = "noaction"
	RestrictTag        = "restrict"
	CascadeTag         = "cascade"
	SetNullTag         = "setnull"
	PrimaryKey         = "PRIMARY KEY"
	Unique             = "UNIQUE"
	ForeignKey         = "FOREIGN KEY"
	No                 = "NO"
	Yes                = "YES"
	Add                = "ADD"
	Drop               = "DROP"
	UserDefined        = "USER-DEFINED"
	Set                = "SET"
	Deferrable         = "DEFERRABLE"
	InitiallyDeferred  = "INITIALLY DEFERRED"
	InitiallyImmediate = "INITIALLY IMMEDIATE"
	NotDeferrable      = "NOT DEFERRABLE"
	Null               = "NULL"
	NotNull            = "NOT NULL"
	Default            = "DEFAULT"
	References         = "REFERENCES"
	NoAction           = "NO ACTION"
	Restrict           = "RESTRICT"
	Cascade            = "CASCADE"
	SetNull            = "SET NULL"
	SetDefault         = "SET DEFAULT"
)
