package shifter

//constants used
const (
	nullTag            = "null"
	primaryKeyTag      = "primary key"
	uniqueKeyTag       = "unique"
	notNullTag         = "not null"
	referencesTag      = "references"
	deleteTag          = "delete"
	updateTag          = "update"
	noActionTag        = "noaction"
	restrictTag        = "restrict"
	cascadeTag         = "cascade"
	setNullTag         = "setnull"
	primaryKey         = "PRIMARY KEY"
	uniqueKey          = "UNIQUE"
	foreignKey         = "FOREIGN KEY"
	No                 = "NO"
	Yes                = "YES"
	Add                = "ADD"
	Drop               = "DROP"
	UserDefined        = "USER-DEFINED"
	Set                = "SET"
	Deferrable         = "DEFERRABLE"
	InitiallyDeferred  = "INITIALLY DEFERRED"
	InitiallyImmediate = "INITIALLY IMMEDIATE"
	NotDeferrable      = "NOT DEFERRABLE"
	Null               = "NULL"
	NotNull            = "NOT NULL"
	Default            = "DEFAULT"
	References         = "REFERENCES"
	NoAction           = "NO ACTION"
	Restrict           = "RESTRICT"
	Cascade            = "CASCADE"
	SetNull            = "SET NULL"
	SetDefault         = "SET DEFAULT"
	PrimaryKeySuffix   = "pkey"
	UniqueKeySuffix    = "key"
	ForeignKeySuffix   = "fkey"
)
