package shifter

//constants used
const (
	nullTag             = "null"
	primaryKeyTag       = "primary key"
	uniqueKeyTag        = "unique"
	notNullTag          = "not null"
	referencesTag       = "references"
	deleteTag           = "delete"
	updateTag           = "update"
	setdefaultTag       = "setdefault"
	noActionTag         = "noaction"
	restrictTag         = "restrict"
	cascadeTag          = "cascade"
	setNullTag          = "setnull"
	primaryKey          = "PRIMARY KEY"
	uniqueKey           = "UNIQUE"
	foreignKey          = "FOREIGN KEY"
	no                  = "NO"
	yes                 = "YES"
	add                 = "ADD"
	drop                = "DROP"
	set                 = "SET"
	userDefined         = "USER-DEFINED"
	deferrable          = "DEFERRABLE"
	initiallyDeferred   = "INITIALLY DEFERRED"
	initiallyImmediate  = "INITIALLY IMMEDIATE"
	notDeferrable       = "NOT DEFERRABLE"
	null                = "NULL"
	notNull             = "NOT NULL"
	defaultField        = "DEFAULT"
	references          = "REFERENCES"
	noAction            = "NO ACTION"
	restrict            = "RESTRICT"
	cascade             = "CASCADE"
	setNull             = "SET NULL"
	setDefault          = "SET DEFAULT"
	primaryKeySuffix    = "pkey"
	uniqueKeySuffix     = "key"
	foreignKeySuffix    = "fkey"
	TriggerTag          = "trigger" //used to create triggers on table.
	HistoryTag          = "history" //used to create history table. Default table_history if after trigger given
	afterInsertTrigger  = "ai"
	afterUpdateTrigger  = "au"
	afterDeleteTrigger  = "ad"
	beforeUpdateTrigger = "bu"
	curPkg              = "shifter \"github.com/mayur-tolexo/pg-shifter\""
)
